services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
      
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
      - "5679:5679"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    env_file:
      - .env
    depends_on:
      - backend

  # orchestration:
  #   image: docker.n8n.io/n8nio/n8n
  #   container_name: n8n-main
  #   restart: always
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_HOST=localhost
  #     - N8N_PORT=5678
  #     - N8N_PROTOCOL=http
  #     - N8N_SECURE_COOKIE=false
  #     - NODE_OPTIONS=--max-old-space-size=1024
  #     - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
  #     - N8N_BLOCK_SVG_AND_ENV_VARS_IN_FILENAMES=false
  #     - BACKEND_URL=${BACKEND_URL}
  #     # Runner Configuration
  #     - N8N_RUNNERS_MODE=external
  #     - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
  #     - N8N_RUNNERS_AUTH_TOKEN=05ti/GEELH2szAGE4zstt5ggGLcgKstf
  #     - N8N_NATIVE_PYTHON_RUNNER=true
  #     - N8N_RUNNERS_BROKER_PORT=5679
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./orchestration/data:/home/node/.n8n

  # n8n-runners:
  #   image: docker.n8n.io/n8nio/runners
  #   container_name: n8n-runners
  #   restart: always
  #   environment:
  #     - N8N_RUNNERS_TASK_BROKER_URI=http://orchestration:5679
  #     - N8N_RUNNERS_AUTH_TOKEN=05ti/GEELH2szAGE4zstt5ggGLcgKstf
  #   depends_on:
  #     - orchestration

  orchestration:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_PYTHON_PATH=/usr/bin/python3
      - NODE_OPTIONS=--max-old-space-size=1024
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_BLOCK_SVG_AND_ENV_VARS_IN_FILENAMES=false
      - BACKEND_URL=${BACKEND_URL}
    env_file:
      - .env
    volumes:
      - ./orchestration/data:/home/node/.n8n
    restart: always